Test job

diff --git a/.github/workflows/smoke-checks.yml b/.github/workflows/smoke-checks.yml
--- a/.github/workflows/smoke-checks.yml
+++ b/.github/workflows/smoke-checks.yml
@@ -31,234 +31,234 @@ env:
   IOS_SIMULATOR_DEVICE: "iPhone 15 Pro (17.2)"
 
 jobs:
-  build-test-app-and-frameworks:
-    name: Build Test App and Frameworks
-    runs-on: macos-14
-    if: ${{ github.event_name != 'push' && github.event.inputs.swiftui_snapshots != 'true' && github.event.inputs.uikit_snapshots != 'true' }}
-    steps:
-    - uses: actions/checkout@v4.1.1
-    - uses: ./.github/actions/ruby-cache
-    - uses: ./.github/actions/xcode-cache
-    - name: Build
-      run: bundle exec fastlane build_test_app_and_frameworks
-      timeout-minutes: 60
-      env:
-        STREAM_VIDEO_SECRET: ${{ secrets.STREAM_VIDEO_SECRET }}
-    - uses: actions/upload-artifact@v3
-      if: success()
-      with:
-        name: cache-derived-data
-        path: |
-          derived_data/Build/**/*.app
-          derived_data/Build/**/*.xctestrun
-          derived_data/Build/**/*.framework
+  # build-test-app-and-frameworks:
+  #   name: Build Test App and Frameworks
+  #   runs-on: macos-14
+  #   if: ${{ github.event_name != 'push' && github.event.inputs.swiftui_snapshots != 'true' && github.event.inputs.uikit_snapshots != 'true' }}
+  #   steps:
+  #   - uses: actions/checkout@v4.1.1
+  #   - uses: ./.github/actions/ruby-cache
+  #   - uses: ./.github/actions/xcode-cache
+  #   - name: Build
+  #     run: bundle exec fastlane build_test_app_and_frameworks
+  #     timeout-minutes: 60
+  #     env:
+  #       STREAM_VIDEO_SECRET: ${{ secrets.STREAM_VIDEO_SECRET }}
+  #   - uses: actions/upload-artifact@v3
+  #     if: success()
+  #     with:
+  #       name: cache-derived-data
+  #       path: |
+  #         derived_data/Build/**/*.app
+  #         derived_data/Build/**/*.xctestrun
+  #         derived_data/Build/**/*.framework
 
-  test-llc-debug:
-    name: Test LLC (Debug)
-    runs-on: macos-14
-    needs: build-test-app-and-frameworks
-    if: ${{ github.event.inputs.swiftui_snapshots != 'true' && github.event.inputs.uikit_snapshots != 'true' }}
-    env:
-      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      GITHUB_PR_NUM: ${{ github.event.number }}
-      STREAM_VIDEO_SECRET: ${{ secrets.STREAM_VIDEO_SECRET }}
-    steps:
-    - uses: actions/checkout@v4.1.1
-      with:
-        fetch-depth: 100
-    - uses: actions/download-artifact@v3
-      with:
-        name: cache-derived-data
-        path: derived_data/Build/
-    - uses: ./.github/actions/bootstrap
-      env:
-        INSTALL_YEETD: true
-    - uses: ./.github/actions/python-cache
-    - name: Run LLC Tests (Debug)
-      run: bundle exec fastlane test device:"${{ env.IOS_SIMULATOR_DEVICE }}" skip_build:true
-      timeout-minutes: 40
-    - name: Get branch name
-      id: get_branch_name
-      run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
-    - name: Run Sonar analysis
-      run: bundle exec fastlane sonar_upload
-      env:
-        BRANCH_NAME: ${{ steps.get_branch_name.outputs.branch }}
-        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
-        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-    - uses: actions/upload-artifact@v3
-      if: failure()
-      with:
-        name: LLC Test Data
-        path: |
-          ~/Library/Logs/scan
-    - uses: 8398a7/action-slack@v3
-      with:
-        status: ${{ job.status }}
-        text: "You shall not pass!"
-        job_name: "Test LLC (Debug)"
-        fields: message,commit,author,action,workflow,job,took
-      env:
-        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
-        MATRIX_CONTEXT: ${{ toJson(matrix) }}
-      if: ${{ github.event_name == 'push' && failure() }}
+  # test-llc-debug:
+  #   name: Test LLC (Debug)
+  #   runs-on: macos-14
+  #   needs: build-test-app-and-frameworks
+  #   if: ${{ github.event.inputs.swiftui_snapshots != 'true' && github.event.inputs.uikit_snapshots != 'true' }}
+  #   env:
+  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #     GITHUB_PR_NUM: ${{ github.event.number }}
+  #     STREAM_VIDEO_SECRET: ${{ secrets.STREAM_VIDEO_SECRET }}
+  #   steps:
+  #   - uses: actions/checkout@v4.1.1
+  #     with:
+  #       fetch-depth: 100
+  #   - uses: actions/download-artifact@v3
+  #     with:
+  #       name: cache-derived-data
+  #       path: derived_data/Build/
+  #   - uses: ./.github/actions/bootstrap
+  #     env:
+  #       INSTALL_YEETD: true
+  #   - uses: ./.github/actions/python-cache
+  #   - name: Run LLC Tests (Debug)
+  #     run: bundle exec fastlane test device:"${{ env.IOS_SIMULATOR_DEVICE }}" skip_build:true
+  #     timeout-minutes: 40
+  #   - name: Get branch name
+  #     id: get_branch_name
+  #     run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
+  #   - name: Run Sonar analysis
+  #     run: bundle exec fastlane sonar_upload
+  #     env:
+  #       BRANCH_NAME: ${{ steps.get_branch_name.outputs.branch }}
+  #       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+  #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+  #   - uses: actions/upload-artifact@v3
+  #     if: failure()
+  #     with:
+  #       name: LLC Test Data
+  #       path: |
+  #         ~/Library/Logs/scan
+  #   - uses: 8398a7/action-slack@v3
+  #     with:
+  #       status: ${{ job.status }}
+  #       text: "You shall not pass!"
+  #       job_name: "Test LLC (Debug)"
+  #       fields: message,commit,author,action,workflow,job,took
+  #     env:
+  #       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+  #       MATRIX_CONTEXT: ${{ toJson(matrix) }}
+  #     if: ${{ github.event_name == 'push' && failure() }}
 
-  test-swiftui-debug:
-    name: Test SwiftUI (Debug)
-    runs-on: macos-14
-    if: ${{ github.event_name != 'push' && github.event.inputs.swiftui_snapshots != 'false' }}
-    env:
-      GITHUB_TOKEN: ${{ secrets.CI_BOT_GITHUB_TOKEN }} # to open a PR
-      GITHUB_PR_NUM: ${{ github.event.number }}
-    steps:
-    - uses: actions/checkout@v4.1.1
-    - uses: ./.github/actions/bootstrap
-      env:
-        INSTALL_YEETD: true
-    - name: Run UI Tests (Debug)
-      run: bundle exec fastlane test_swiftui device:"${{ env.IOS_SIMULATOR_DEVICE }}" record:${{ github.event.inputs.swiftui_snapshots }}
-      timeout-minutes: 40
-    - name: Parse xcresult
-      if: failure()
-      run: |
-        brew install chargepoint/xcparse/xcparse
-        xcparse screenshots fastlane/test_output/StreamVideoSwiftUI.xcresult fastlane/test_output/snapshots --test
-    - uses: actions/upload-artifact@v3
-      if: failure()
-      with:
-        name: SwiftUI Test Data
-        path: |
-          ~/Library/Logs/scan
-          fastlane/test_output/snapshots
+  # test-swiftui-debug:
+  #   name: Test SwiftUI (Debug)
+  #   runs-on: macos-14
+  #   if: ${{ github.event_name != 'push' && github.event.inputs.swiftui_snapshots != 'false' }}
+  #   env:
+  #     GITHUB_TOKEN: ${{ secrets.CI_BOT_GITHUB_TOKEN }} # to open a PR
+  #     GITHUB_PR_NUM: ${{ github.event.number }}
+  #   steps:
+  #   - uses: actions/checkout@v4.1.1
+  #   - uses: ./.github/actions/bootstrap
+  #     env:
+  #       INSTALL_YEETD: true
+  #   - name: Run UI Tests (Debug)
+  #     run: bundle exec fastlane test_swiftui device:"${{ env.IOS_SIMULATOR_DEVICE }}" record:${{ github.event.inputs.swiftui_snapshots }}
+  #     timeout-minutes: 40
+  #   - name: Parse xcresult
+  #     if: failure()
+  #     run: |
+  #       brew install chargepoint/xcparse/xcparse
+  #       xcparse screenshots fastlane/test_output/StreamVideoSwiftUI.xcresult fastlane/test_output/snapshots --test
+  #   - uses: actions/upload-artifact@v3
+  #     if: failure()
+  #     with:
+  #       name: SwiftUI Test Data
+  #       path: |
+  #         ~/Library/Logs/scan
+  #         fastlane/test_output/snapshots
 
-  test-uikit-debug:
-    name: Test UIKit (Debug)
-    runs-on: macos-14
-    if: ${{ github.event_name != 'push' && github.event.inputs.uikit_snapshots != 'false' }}
-    env:
-      GITHUB_TOKEN: ${{ secrets.CI_BOT_GITHUB_TOKEN }} # to open a PR
-      GITHUB_PR_NUM: ${{ github.event.number }}
-    steps:
-    - uses: actions/checkout@v4.1.1
-    - uses: ./.github/actions/bootstrap
-      env:
-        INSTALL_YEETD: true
-    - name: Run UI Tests (Debug)
-      run: bundle exec fastlane test_uikit device:"${{ env.IOS_SIMULATOR_DEVICE }}" record:${{ github.event.inputs.uikit_snapshots }}
-      timeout-minutes: 40
-    - name: Parse xcresult
-      if: failure()
-      run: |
-        brew install chargepoint/xcparse/xcparse
-        xcparse screenshots fastlane/test_output/StreamVideoUIKit.xcresult fastlane/test_output/snapshots --test
-    - uses: actions/upload-artifact@v3
-      if: failure()
-      with:
-        name: UIKit Test Data
-        path: |
-          ~/Library/Logs/scan
-          fastlane/test_output/snapshots
+  # test-uikit-debug:
+  #   name: Test UIKit (Debug)
+  #   runs-on: macos-14
+  #   if: ${{ github.event_name != 'push' && github.event.inputs.uikit_snapshots != 'false' }}
+  #   env:
+  #     GITHUB_TOKEN: ${{ secrets.CI_BOT_GITHUB_TOKEN }} # to open a PR
+  #     GITHUB_PR_NUM: ${{ github.event.number }}
+  #   steps:
+  #   - uses: actions/checkout@v4.1.1
+  #   - uses: ./.github/actions/bootstrap
+  #     env:
+  #       INSTALL_YEETD: true
+  #   - name: Run UI Tests (Debug)
+  #     run: bundle exec fastlane test_uikit device:"${{ env.IOS_SIMULATOR_DEVICE }}" record:${{ github.event.inputs.uikit_snapshots }}
+  #     timeout-minutes: 40
+  #   - name: Parse xcresult
+  #     if: failure()
+  #     run: |
+  #       brew install chargepoint/xcparse/xcparse
+  #       xcparse screenshots fastlane/test_output/StreamVideoUIKit.xcresult fastlane/test_output/snapshots --test
+  #   - uses: actions/upload-artifact@v3
+  #     if: failure()
+  #     with:
+  #       name: UIKit Test Data
+  #       path: |
+  #         ~/Library/Logs/scan
+  #         fastlane/test_output/snapshots
 
-  build-apps:
-    name: Build Demo Apps
-    runs-on: macos-14
-    needs: build-test-app-and-frameworks
-    if: ${{ github.event_name != 'push' && github.event.inputs.swiftui_snapshots != 'true' && github.event.inputs.uikit_snapshots != 'true' }}
-    env:
-      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      GITHUB_PR_NUM: ${{ github.event.number }}
-    steps:
-    - uses: actions/checkout@v4.1.1
-    - uses: actions/download-artifact@v3
-      with:
-        name: cache-derived-data
-        path: derived_data/Build/
-    - uses: ./.github/actions/ruby-cache
-    - uses: ./.github/actions/xcode-cache
-    - name: Build SwiftUI Demo App
-      run: bundle exec fastlane build_swiftui_demo
-    - name: Build UIKit Demo App
-      run: bundle exec fastlane build_uikit_demo
-    - name: Build Docs Test Project
-      run: bundle exec fastlane build_docs_test
+  # build-apps:
+  #   name: Build Demo Apps
+  #   runs-on: macos-14
+  #   needs: build-test-app-and-frameworks
+  #   if: ${{ github.event_name != 'push' && github.event.inputs.swiftui_snapshots != 'true' && github.event.inputs.uikit_snapshots != 'true' }}
+  #   env:
+  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #     GITHUB_PR_NUM: ${{ github.event.number }}
+  #   steps:
+  #   - uses: actions/checkout@v4.1.1
+  #   - uses: actions/download-artifact@v3
+  #     with:
+  #       name: cache-derived-data
+  #       path: derived_data/Build/
+  #   - uses: ./.github/actions/ruby-cache
+  #   - uses: ./.github/actions/xcode-cache
+  #   - name: Build SwiftUI Demo App
+  #     run: bundle exec fastlane build_swiftui_demo
+  #   - name: Build UIKit Demo App
+  #     run: bundle exec fastlane build_uikit_demo
+  #   - name: Build Docs Test Project
+  #     run: bundle exec fastlane build_docs_test
 
-  test-e2e-debug:
-    name: Test E2E UI (Debug)
-    runs-on: macos-14
-    if: ${{ github.event_name != 'push' && github.event.inputs.swiftui_snapshots != 'true' && github.event.inputs.uikit_snapshots != 'true' }}
-    needs:
-      - allure_testops_launch
-      - build-test-app-and-frameworks
-    env:
-      LAUNCH_ID: ${{ needs.allure_testops_launch.outputs.launch_id }}
-      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      GITHUB_PR_NUM: ${{ github.event.number }}
-      ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
-    strategy:
-      matrix:
-        batch: [0, 1]
-      fail-fast: false
-    steps:
-    - uses: actions/checkout@v4.1.1
-    - uses: actions/download-artifact@v3
-      with:
-        name: cache-derived-data
-        path: derived_data/Build/
-    - uses: ./.github/actions/bootstrap
-      env:
-        INSTALL_ALLURE: true
-        INSTALL_VIDEO_BUDDY: true
-        INSTALL_YEETD: true
-    - name: Run UI Tests (Debug)
-      run: bundle exec fastlane test_e2e device:"${{ env.IOS_SIMULATOR_DEVICE }}" batch:'${{ matrix.batch }}' test_without_building:true
-      timeout-minutes: 60
-      env:
-        MATRIX_SIZE: ${{ strategy.job-total }}
-        STREAM_SDK_TEST_APP: ${{ secrets.STREAM_SDK_TEST_APP }}
-        STREAM_SDK_TEST_ACCOUNT_EMAIL: ${{ secrets.STREAM_SDK_TEST_ACCOUNT_EMAIL }}
-        STREAM_SDK_TEST_ACCOUNT_PASSWORD: ${{ secrets.STREAM_SDK_TEST_ACCOUNT_PASSWORD }}
-        STREAM_SDK_TEST_ACCOUNT_OTP_SECRET: ${{ secrets.STREAM_SDK_TEST_ACCOUNT_OTP_SECRET }}
-        STREAM_VIDEO_SECRET: ${{ secrets.STREAM_VIDEO_SECRET }}
-    - name: Allure TestOps Upload
-      if: env.LAUNCH_ID != '' && (success() || failure())
-      run: bundle exec fastlane allure_upload launch_id:$LAUNCH_ID
-    - name: Allure TestOps Launch Removal
-      if: env.LAUNCH_ID != '' && cancelled()
-      run: bundle exec fastlane allure_launch_removal launch_id:$LAUNCH_ID
-    - name: Parse xcresult
-      if: failure()
-      run: |
-        brew install chargepoint/xcparse/xcparse
-        xcparse logs fastlane/test_output/DemoApp.xcresult fastlane/test_output/logs/
-    - uses: actions/upload-artifact@v3
-      if: failure()
-      with:
-        name: E2E Test Data ${{ matrix.batch }}
-        path: |
-          ~/Library/Logs/scan
-          fastlane/recordings
-          fastlane/*.log
-          fastlane/test_output/logs/*/Diagnostics/SwiftUIDemoAppUITests-*/*/*.txt
-          fastlane/test_output/logs/*/Diagnostics/simctl_diagnostics/DiagnosticReports/*
+  # test-e2e-debug:
+  #   name: Test E2E UI (Debug)
+  #   runs-on: macos-14
+  #   if: ${{ github.event_name != 'push' && github.event.inputs.swiftui_snapshots != 'true' && github.event.inputs.uikit_snapshots != 'true' }}
+  #   needs:
+  #     - allure_testops_launch
+  #     - build-test-app-and-frameworks
+  #   env:
+  #     LAUNCH_ID: ${{ needs.allure_testops_launch.outputs.launch_id }}
+  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #     GITHUB_PR_NUM: ${{ github.event.number }}
+  #     ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
+  #   strategy:
+  #     matrix:
+  #       batch: [0, 1]
+  #     fail-fast: false
+  #   steps:
+  #   - uses: actions/checkout@v4.1.1
+  #   - uses: actions/download-artifact@v3
+  #     with:
+  #       name: cache-derived-data
+  #       path: derived_data/Build/
+  #   - uses: ./.github/actions/bootstrap
+  #     env:
+  #       INSTALL_ALLURE: true
+  #       INSTALL_VIDEO_BUDDY: true
+  #       INSTALL_YEETD: true
+  #   - name: Run UI Tests (Debug)
+  #     run: bundle exec fastlane test_e2e device:"${{ env.IOS_SIMULATOR_DEVICE }}" batch:'${{ matrix.batch }}' test_without_building:true
+  #     timeout-minutes: 60
+  #     env:
+  #       MATRIX_SIZE: ${{ strategy.job-total }}
+  #       STREAM_SDK_TEST_APP: ${{ secrets.STREAM_SDK_TEST_APP }}
+  #       STREAM_SDK_TEST_ACCOUNT_EMAIL: ${{ secrets.STREAM_SDK_TEST_ACCOUNT_EMAIL }}
+  #       STREAM_SDK_TEST_ACCOUNT_PASSWORD: ${{ secrets.STREAM_SDK_TEST_ACCOUNT_PASSWORD }}
+  #       STREAM_SDK_TEST_ACCOUNT_OTP_SECRET: ${{ secrets.STREAM_SDK_TEST_ACCOUNT_OTP_SECRET }}
+  #       STREAM_VIDEO_SECRET: ${{ secrets.STREAM_VIDEO_SECRET }}
+  #   - name: Allure TestOps Upload
+  #     if: env.LAUNCH_ID != '' && (success() || failure())
+  #     run: bundle exec fastlane allure_upload launch_id:$LAUNCH_ID
+  #   - name: Allure TestOps Launch Removal
+  #     if: env.LAUNCH_ID != '' && cancelled()
+  #     run: bundle exec fastlane allure_launch_removal launch_id:$LAUNCH_ID
+  #   - name: Parse xcresult
+  #     if: failure()
+  #     run: |
+  #       brew install chargepoint/xcparse/xcparse
+  #       xcparse logs fastlane/test_output/DemoApp.xcresult fastlane/test_output/logs/
+  #   - uses: actions/upload-artifact@v3
+  #     if: failure()
+  #     with:
+  #       name: E2E Test Data ${{ matrix.batch }}
+  #       path: |
+  #         ~/Library/Logs/scan
+  #         fastlane/recordings
+  #         fastlane/*.log
+  #         fastlane/test_output/logs/*/Diagnostics/SwiftUIDemoAppUITests-*/*/*.txt
+  #         fastlane/test_output/logs/*/Diagnostics/simctl_diagnostics/DiagnosticReports/*
 
-  allure_testops_launch:
-    name: Launch Allure TestOps
-    runs-on: macos-13
-    if: ${{ github.event_name != 'push' && github.event.inputs.swiftui_snapshots != 'true' && github.event.inputs.uikit_snapshots != 'true' }}
-    outputs:
-      launch_id: ${{ steps.get_launch_id.outputs.launch_id }}
-    steps:
-    - uses: actions/checkout@v4.1.1
-    - uses: ./.github/actions/ruby-cache
-    - name: Launch Allure TestOps
-      run: bundle exec fastlane allure_launch
-      env:
-        ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        GITHUB_EVENT: ${{ toJson(github.event) }}
-    - id: get_launch_id
-      run: echo "launch_id=${{env.LAUNCH_ID}}" >> $GITHUB_OUTPUT
-      if: env.LAUNCH_ID != ''
+  # allure_testops_launch:
+  #   name: Launch Allure TestOps
+  #   runs-on: macos-13
+  #   if: ${{ github.event_name != 'push' && github.event.inputs.swiftui_snapshots != 'true' && github.event.inputs.uikit_snapshots != 'true' }}
+  #   outputs:
+  #     launch_id: ${{ steps.get_launch_id.outputs.launch_id }}
+  #   steps:
+  #   - uses: actions/checkout@v4.1.1
+  #   - uses: ./.github/actions/ruby-cache
+  #   - name: Launch Allure TestOps
+  #     run: bundle exec fastlane allure_launch
+  #     env:
+  #       ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
+  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #       GITHUB_EVENT: ${{ toJson(github.event) }}
+  #   - id: get_launch_id
+  #     run: echo "launch_id=${{env.LAUNCH_ID}}" >> $GITHUB_OUTPUT
+  #     if: env.LAUNCH_ID != ''
 
   build-xcode15:
     name: Build SDKs (Xcode 15.0)
